repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.6
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
